version: '3.1'

services:
  cakephp3:
    image: webdevops/php-apache-dev:7.3
    container_name: cakephp3
    volumes:
      - ".:/app"
    ports:
      - 8080:80
    links:
      - postgres:postgres
    restart: always

  postgres:
    container_name: postgres
    restart: always
    image: postgres:latest
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    tmpfs:
      - /var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "8081:80"
    depends_on:
      - postgres
